##############################################################################
#                                                                            #
#  bashsieve.conf                                                            #
#                                                                            #
#  Main configuration file for the 'bashsieve.sh' script.                    #
#                                                                            #
#  The options inside this file cannot be set via command-line arguments.    #
#                                                                            #
#  Important notice:    Ensure that there are no spaces around the equal     #
#                       signs of all options. Otherwise settings will not    #
#                       be applied correctly or BashSieve may even crash     #
#                       under certain circumstances.                         #
#                                                                            #
##############################################################################

# Verbose mode to also print the messages written to the log on the shell.
#
#   0   = disabled (default)
#   1   = enabled
#
verbose=0
